# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install pnpm and tsx CLI
RUN npm install -g pnpm tsx

# Copy project files
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running postinstall scripts
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy all sources
COPY . .

# Run the MCP server with tsx via stdio transport
CMD ["tsx", "custom-mcp-server/index.ts"]
